"""Country name aliases -> canonical (common) name. GENERATED FILE.

Built by scripts/make_country_aliases.py from the mledoze/countries dataset
(https://github.com/mledoze/countries, Open Database License 1.0). Keys are
normalized with verify._clean() + casefold; values are the dataset's common
names. Regenerate with:  python scripts/make_country_aliases.py --fetch
"""

COUNTRY_ALIASES = {
    'aaland': 'Åland Islands',
    'afganistan': 'Afghanistan',
    'afghanistan': 'Afghanistan',
    'ahvenanmaa': 'Åland Islands',
    'al ittihad al qumuri': 'Comoros',
    'al jumhuriyah al libnaniyah': 'Lebanon',
    'al jumhuriyah al ʻarabiyah as suriyah': 'Syria',
    'al jumhuriyyah al yamaniyyah': 'Yemen',
    'al jumhuriyyah al ʾislamiyyah al muritaniyyah': 'Mauritania',
    'al jumhuriyyah at tunisiyyah': 'Tunisia',
    'al mamlakah al arabiyyah as suudiyyah': 'Saudi Arabia',
    'al mamlakah al magribiyah': 'Morocco',
    'al mamlakah al urduniyah al hashimiyah': 'Jordan',
    'aland': 'Åland Islands',
    'aland islands': 'Åland Islands',
    'albania': 'Albania',
    'algeria': 'Algeria',
    'algerie': 'Algeria',
    'amelika samoa': 'American Samoa',
    'america': 'United States',
    'american samoa': 'American Samoa',
    'amerika samoa': 'American Samoa',
    'andorra': 'Andorra',
    'angola': 'Angola',
    'anguilla': 'Anguilla',
    'antarctica': 'Antarctica',
    'antigua and barbuda': 'Antigua and Barbuda',
    'aolepan aorokin majel': 'Marshall Islands',
    'aotearoa': 'New Zealand',
    'arab republic of egypt': 'Egypt',
    'argentina': 'Argentina',
    'argentine republic': 'Argentina',
    'armenia': 'Armenia',
    'aruba': 'Aruba',
    'as sumal': 'Somalia',
    'australia': 'Australia',
    'austria': 'Austria',
    'azerbaijan': 'Azerbaijan',
    'azərbaycan respublikası': 'Azerbaijan',
    'bahamas': 'Bahamas',
    'bahrain': 'Bahrain',
    'bailiwick of guernsey': 'Guernsey',
    'bailiwick of jersey': 'Jersey',
    'bailliage de guernesey': 'Guernsey',
    'bailliage de jerri': 'Jersey',
    'bailliage de jersey': 'Jersey',
    'bangladesh': 'Bangladesh',
    'barbados': 'Barbados',
    'belarus': 'Belarus',
    'belgie': 'Belgium',
    'belgien': 'Belgium',
    'belgique': 'Belgium',
    'belgium': 'Belgium',
    'belize': 'Belize',
    'beluu er a belau': 'Palau',
    'benin': 'Benin',
    'bermuda': 'Bermuda',
    'bes islands': 'Caribbean Netherlands',
    'bharat': 'India',
    'bharat ganrajya': 'India',
    'bhutan': 'Bhutan',
    'bielarus': 'Belarus',
    'bolivarian republic of venezuela': 'Venezuela',
    'bolivia': 'Bolivia',
    'bolivia plurinational state of': 'Bolivia',
    'bonaire sint eustatius and saba': 'Caribbean Netherlands',
    'bosnia and herzegovina': 'Bosnia and Herzegovina',
    'bosnia herzegovina': 'Bosnia and Herzegovina',
    'botswana': 'Botswana',
    'bouvet island': 'Bouvet Island',
    'bouvet øya': 'Bouvet Island',
    'bouvetøya': 'Bouvet Island',
    'brasil': 'Brazil',
    'brazil': 'Brazil',
    'britain': 'United Kingdom',
    'british indian ocean territory': 'British Indian Ocean Territory',
    'british virgin islands': 'British Virgin Islands',
    'brunei': 'Brunei',
    'brunei darussalam': 'Brunei',
    'bulgaria': 'Bulgaria',
    'buliwya': 'Bolivia',
    'buliwya mamallaqta': 'Bolivia',
    'bundesrepublik deutschland': 'Germany',
    'burkina faso': 'Burkina Faso',
    'burma': 'Myanmar',
    'burundi': 'Burundi',
    'cambodia': 'Cambodia',
    'cameroon': 'Cameroon',
    'canada': 'Canada',
    'cape verde': 'Cape Verde',
    'caribbean netherlands': 'Caribbean Netherlands',
    'cayman islands': 'Cayman Islands',
    'central african republic': 'Central African Republic',
    'ceska republika': 'Czechia',
    'cesko': 'Czechia',
    'chad': 'Chad',
    'chile': 'Chile',
    'china': 'China',
    'chinese taipei': 'Taiwan',
    'choson minjujuui inmin konghwaguk': 'North Korea',
    'christmas island': 'Christmas Island',
    'co operative republic of guyana': 'Guyana',
    'cocos (keeling) islands': 'Cocos (Keeling) Islands',
    'cocos islands': 'Cocos (Keeling) Islands',
    'collectivite de saint barthelemy': 'Saint Barthélemy',
    'collectivite de saint martin': 'Saint Martin',
    'collectivite territoriale de saint pierre et miquelon': 'Saint Pierre and Miquelon',
    'collectivity of saint barthelemy': 'Saint Barthélemy',
    'collectivity of saint martin': 'Saint Martin',
    'colombia': 'Colombia',
    'commonwealth of australia': 'Australia',
    'commonwealth of dominica': 'Dominica',
    'commonwealth of puerto rico': 'Puerto Rico',
    'commonwealth of the bahamas': 'Bahamas',
    'commonwealth of the northern mariana islands': 'Northern Mariana Islands',
    'comoros': 'Comoros',
    'cong hoa xa hoi chu nghia viet nam': 'Vietnam',
    'congo': 'Congo',
    'congo brazzaville': 'Congo',
    'congo kinshasa': 'DR Congo',
    'congo the democratic republic of the': 'DR Congo',
    'cook islands': 'Cook Islands',
    'costa rica': 'Costa Rica',
    'cote divoire': 'Ivory Coast',
    'country of curacao': 'Curaçao',
    'crna gora': 'Montenegro',
    'croatia': 'Croatia',
    'cuba': 'Cuba',
    'cumhuriyi tocikiston': 'Tajikistan',
    'curacao': 'Curaçao',
    'cyprus': 'Cyprus',
    'czech republic': 'Czechia',
    'czechia': 'Czechia',
    'danmark': 'Denmark',
    'dawlat al kuwait': 'Kuwait',
    'dawlat filastin': 'Palestine',
    'dawlat iritriya': 'Eritrea',
    'dawlat libya': 'Libya',
    'dawlat qatar': 'Qatar',
    'democratic peoples republic of korea': 'North Korea',
    'democratic republic of congo': 'DR Congo',
    'democratic republic of sao tome and principe': 'São Tomé and Príncipe',
    'democratic republic of the congo': 'DR Congo',
    'democratic republic of timor leste': 'Timor-Leste',
    'democratic socialist republic of sri lanka': 'Sri Lanka',
    'denmark': 'Denmark',
    'departement de mayotte': 'Mayotte',
    'department of mayotte': 'Mayotte',
    'dhivehi raajjeyge jumhooriyya': 'Maldives',
    'djibouti': 'Djibouti',
    'dominica': 'Dominica',
    'dominican republic': 'Dominican Republic',
    'dominique': 'Dominica',
    'dprk': 'North Korea',
    'dr congo': 'DR Congo',
    'drc': 'DR Congo',
    'dzayer': 'Algeria',
    'east timor': 'Timor-Leste',
    'ecuador': 'Ecuador',
    'eesti': 'Estonia',
    'eesti vabariik': 'Estonia',
    'egypt': 'Egypt',
    'eire': 'Ireland',
    'el salvador': 'El Salvador',
    'ellada': 'Greece',
    'ellan vannin': 'Isle of Man',
    'emirates': 'United Arab Emirates',
    'equatorial guinea': 'Equatorial Guinea',
    'eritrea': 'Eritrea',
    'estado libre asociado de puerto rico': 'Puerto Rico',
    'estado plurinacional de bolivia': 'Bolivia',
    'estados unidos mexicanos': 'Mexico',
    'estonia': 'Estonia',
    'eswatini': 'Eswatini',
    'ethiopia': 'Ethiopia',
    'faeroe islands': 'Faroe Islands',
    'falkland islands': 'Falkland Islands',
    'falkland islands (malvinas)': 'Falkland Islands',
    'faroe islands': 'Faroe Islands',
    'federal democratic republic of ethiopia': 'Ethiopia',
    'federal democratic republic of nepal': 'Nepal',
    'federal republic of germany': 'Germany',
    'federal republic of nigeria': 'Nigeria',
    'federal republic of somalia': 'Somalia',
    'federated states of micronesia': 'Micronesia',
    'federation of saint christopher and nevis': 'Saint Kitts and Nevis',
    'federative republic of brazil': 'Brazil',
    'fiji': 'Fiji',
    'fiji ganarajya': 'Fiji',
    'finland': 'Finland',
    'france': 'France',
    'french guiana': 'French Guiana',
    'french polynesia': 'French Polynesia',
    'french republic': 'France',
    'french southern and antarctic lands': 'French Southern and Antarctic Lands',
    'french southern territories': 'French Southern and Antarctic Lands',
    'furstentum liechtenstein': 'Liechtenstein',
    'færøerne': 'Faroe Islands',
    'føroyar': 'Faroe Islands',
    'gabon': 'Gabon',
    'gabonese republic': 'Gabon',
    'gabuuti': 'Djibouti',
    'gabuutih ummuuno': 'Djibouti',
    'gambia': 'Gambia',
    'georgia': 'Georgia',
    'germany': 'Germany',
    'ghana': 'Ghana',
    'gibraltar': 'Gibraltar',
    'gonoprojatontri bangladesh': 'Bangladesh',
    'grand duche de luxembourg': 'Luxembourg',
    'grand duchy of luxembourg': 'Luxembourg',
    'great britain': 'United Kingdom',
    'greece': 'Greece',
    'greenland': 'Greenland',
    'grenada': 'Grenada',
    'grossherzogtum luxemburg': 'Luxembourg',
    'groussherzogtum letzebuerg': 'Luxembourg',
    'grønland': 'Greenland',
    'guadeloupe': 'Guadeloupe',
    'guahan': 'Guam',
    'guam': 'Guam',
    'guatemala': 'Guatemala',
    'guernsey': 'Guernsey',
    'guiana': 'French Guiana',
    'guinea': 'Guinea',
    'guinea bissau': 'Guinea-Bissau',
    'guyana': 'Guyana',
    'guyane': 'French Guiana',
    'gwadloup': 'Guadeloupe',
    'haiti': 'Haiti',
    'hashemite kingdom of jordan': 'Jordan',
    'hayastan': 'Armenia',
    'heard island and mcdonald islands': 'Heard Island and McDonald Islands',
    'hellenic republic': 'Greece',
    'holland': 'Netherlands',
    'holy see (vatican city state)': 'Vatican City',
    'honduras': 'Honduras',
    'hong kong': 'Hong Kong',
    'hong kong special administrative region of the peoples republic of china': 'Hong Kong',
    'hrvatska': 'Croatia',
    'hungary': 'Hungary',
    'iceland': 'Iceland',
    'ilankai': 'Sri Lanka',
    'independen stet bilong papua niugini': 'Papua New Guinea',
    'independent and sovereign republic of kiribati': 'Kiribati',
    'independent state of papua new guinea': 'Papua New Guinea',
    'independent state of samoa': 'Samoa',
    'india': 'India',
    'indonesia': 'Indonesia',
    'iran': 'Iran',
    'iran islamic republic of': 'Iran',
    'iraq': 'Iraq',
    'ireland': 'Ireland',
    'iritriya': 'Eritrea',
    'islami jumhuriyaeh pakistan': 'Pakistan',
    'islamic republic of afghanistan': 'Afghanistan',
    'islamic republic of iran': 'Iran',
    'islamic republic of mauritania': 'Mauritania',
    'islamic republic of pakistan': 'Pakistan',
    'island': 'Iceland',
    'islas malvinas': 'Falkland Islands',
    'isle of man': 'Isle of Man',
    'israel': 'Israel',
    'italian republic': 'Italy',
    'italy': 'Italy',
    'ivory coast': 'Ivory Coast',
    'jabuuti': 'Djibouti',
    'jamaica': 'Jamaica',
    'jamhuri ya kenya': 'Kenya',
    'jamhuri ya muungano wa tanzania': 'Tanzania',
    'jamhuri ya uganda': 'Uganda',
    'jamhuuriyadda federaalka soomaaliya': 'Somalia',
    'jamhuuriyadda jabuuti': 'Djibouti',
    'japan': 'Japan',
    'jersey': 'Jersey',
    'jomhuri ye eslami ye iran': 'Iran',
    'jordan': 'Jordan',
    'jumhuriyat as sudan': 'Sudan',
    'jumhuriyyat al iraq': 'Iraq',
    'jumhuriyyat as sumal al fideraliyya': 'Somalia',
    'kazakhstan': 'Kazakhstan',
    'keeling islands': 'Cocos (Keeling) Islands',
    'kenya': 'Kenya',
    'kingdom of bahrain': 'Bahrain',
    'kingdom of belgium': 'Belgium',
    'kingdom of bhutan': 'Bhutan',
    'kingdom of cambodia': 'Cambodia',
    'kingdom of denmark': 'Denmark',
    'kingdom of eswatini': 'Eswatini',
    'kingdom of lesotho': 'Lesotho',
    'kingdom of morocco': 'Morocco',
    'kingdom of norway': 'Norway',
    'kingdom of saudi arabia': 'Saudi Arabia',
    'kingdom of spain': 'Spain',
    'kingdom of sweden': 'Sweden',
    'kingdom of thailand': 'Thailand',
    'kingdom of the netherlands': 'Netherlands',
    'kingdom of tonga': 'Tonga',
    'kiribati': 'Kiribati',
    'kongeriget danmark': 'Denmark',
    'kongeriket noreg': 'Norway',
    'kongeriket norge': 'Norway',
    'konigreich belgien': 'Belgium',
    'koninkrijk belgie': 'Belgium',
    'konungariket sverige': 'Sweden',
    'korea democratic peoples republic of': 'North Korea',
    'korea republic of': 'South Korea',
    'korsou': 'Curaçao',
    'kosovo': 'Kosovo',
    'kuki airani': 'Cook Islands',
    'kuwait': 'Kuwait',
    'kypros': 'Cyprus',
    'kyrgyz republic': 'Kyrgyzstan',
    'kyrgyz respublikasy': 'Kyrgyzstan',
    'kyrgyzstan': 'Kyrgyzstan',
    'kıbrıs': 'Cyprus',
    'kıbrıs cumhuriyeti': 'Cyprus',
    'land curacao': 'Curaçao',
    'lao': 'Laos',
    'lao peoples democratic republic': 'Laos',
    'laos': 'Laos',
    'latvia': 'Latvia',
    'latvijas republika': 'Latvia',
    'lebanese republic': 'Lebanon',
    'lebanon': 'Lebanon',
    'lefatshe la botswana': 'Botswana',
    'lesotho': 'Lesotho',
    'liberia': 'Liberia',
    'libya': 'Libya',
    'liechtenstein': 'Liechtenstein',
    'lietuvos respublika': 'Lithuania',
    'lithuania': 'Lithuania',
    'loktantrik ganatantra nepal': 'Nepal',
    'luxembourg': 'Luxembourg',
    'lyðveldið island': 'Iceland',
    'macao': 'Macau',
    'macao special administrative region of the peoples republic of china': 'Macau',
    'macau': 'Macau',
    'macedonia': 'North Macedonia',
    'macedonia the former yugoslav republic of': 'North Macedonia',
    'madagascar': 'Madagascar',
    'malawi': 'Malawi',
    'malaysia': 'Malaysia',
    'maldive islands': 'Maldives',
    'maldives': 'Maldives',
    'mali': 'Mali',
    'malo saʻoloto tutoʻatasi o samoa': 'Samoa',
    'malta': 'Malta',
    'mamlakat al bahrayn': 'Bahrain',
    'mann': 'Isle of Man',
    'mannin': 'Isle of Man',
    'marshall islands': 'Marshall Islands',
    'martinique': 'Martinique',
    'matanitu ko viti': 'Fiji',
    'mauritania': 'Mauritania',
    'mauritius': 'Mauritius',
    'mayotte': 'Mayotte',
    'medinat yisrael': 'Israel',
    'mexicanos': 'Mexico',
    'mexico': 'Mexico',
    'micronesia': 'Micronesia',
    'micronesia federated states of': 'Micronesia',
    'moldova': 'Moldova',
    'moldova republic of': 'Moldova',
    'monaco': 'Monaco',
    'mongolia': 'Mongolia',
    'montenegro': 'Montenegro',
    'montserrat': 'Montserrat',
    'morocco': 'Morocco',
    'most serene republic of san marino': 'San Marino',
    'mozambique': 'Mozambique',
    'muso oa lesotho': 'Lesotho',
    'myanmar': 'Myanmar',
    'naijiria': 'Nigeria',
    'namibia': 'Namibia',
    'namibie': 'Namibia',
    'naoero': 'Nauru',
    'nation of brunei': 'Brunei',
    'nation of brunei abode of peace': 'Brunei',
    'nauru': 'Nauru',
    'nederland': 'Netherlands',
    'nepal': 'Nepal',
    'netherlands': 'Netherlands',
    'new caledonia': 'New Caledonia',
    'new zealand': 'New Zealand',
    'ngwane': 'Eswatini',
    'nicaragua': 'Nicaragua',
    'niger': 'Niger',
    'nigeria': 'Nigeria',
    'nihon': 'Japan',
    'nijar': 'Niger',
    'nijeriya': 'Nigeria',
    'nippon': 'Japan',
    'niue': 'Niue',
    'noreg': 'Norway',
    'norfolk island': 'Norfolk Island',
    'norge': 'Norway',
    'north korea': 'North Korea',
    'north macedonia': 'North Macedonia',
    'northern mariana islands': 'Northern Mariana Islands',
    'norway': 'Norway',
    'oesterreich': 'Austria',
    'oman': 'Oman',
    'oriental republic of uruguay': 'Uruguay',
    'osterreich': 'Austria',
    'ozbekiston respublikasi': 'Uzbekistan',
    'pais korsou': 'Curaçao',
    'pakistan': 'Pakistan',
    'palau': 'Palau',
    'palestine': 'Palestine',
    'palestine state of': 'Palestine',
    'panama': 'Panama',
    'papua new guinea': 'Papua New Guinea',
    'paraguay': 'Paraguay',
    'peoples democratic republic of algeria': 'Algeria',
    'peoples republic of bangladesh': 'Bangladesh',
    'peoples republic of china': 'China',
    'peru': 'Peru',
    'philippines': 'Philippines',
    'pitcairn': 'Pitcairn Islands',
    'pitcairn group of islands': 'Pitcairn Islands',
    'pitcairn henderson ducie and oeno islands': 'Pitcairn Islands',
    'pitcairn islands': 'Pitcairn Islands',
    'pleasant island': 'Nauru',
    'plurinational state of bolivia': 'Bolivia',
    'poblacht na heireann': 'Ireland',
    'poland': 'Poland',
    'polynesie francaise': 'French Polynesia',
    'porinetia farani': 'French Polynesia',
    'portugal': 'Portugal',
    'portuguesa': 'Portugal',
    'portuguese republic': 'Portugal',
    'prathet': 'Thailand',
    'principality of andorra': 'Andorra',
    'principality of liechtenstein': 'Liechtenstein',
    'principality of monaco': 'Monaco',
    'principat dandorra': 'Andorra',
    'principaute de monaco': 'Monaco',
    'puerto rico': 'Puerto Rico',
    'pyidaunzu thanmada myama nainngandaw': 'Myanmar',
    'qatar': 'Qatar',
    'qazaqstan': 'Kazakhstan',
    'qazaqstan respublikası': 'Kazakhstan',
    'ratcha anachak thai': 'Thailand',
    'regiao administrativa especial de macau da republica popular da china': 'Macau',
    'reino de espana': 'Spain',
    'repiblik ayiti': 'Haiti',
    'repiblik sesel': 'Seychelles',
    'repoblikani madagasikara': 'Madagascar',
    'repubblica di san marino': 'San Marino',
    'repubblica italiana': 'Italy',
    'repubblika ta malta': 'Malta',
    'republic of albania': 'Albania',
    'republic of angola': 'Angola',
    'republic of armenia': 'Armenia',
    'republic of austria': 'Austria',
    'republic of azerbaijan': 'Azerbaijan',
    'republic of belarus': 'Belarus',
    'republic of benin': 'Benin',
    'republic of botswana': 'Botswana',
    'republic of bulgaria': 'Bulgaria',
    'republic of burundi': 'Burundi',
    'republic of cabo verde': 'Cape Verde',
    'republic of cameroon': 'Cameroon',
    'republic of chad': 'Chad',
    'republic of chile': 'Chile',
    'republic of china': 'Taiwan',
    'republic of china (taiwan)': 'Taiwan',
    'republic of colombia': 'Colombia',
    'republic of costa rica': 'Costa Rica',
    'republic of cote divoire': 'Ivory Coast',
    'republic of croatia': 'Croatia',
    'republic of cuba': 'Cuba',
    'republic of cyprus': 'Cyprus',
    'republic of djibouti': 'Djibouti',
    'republic of ecuador': 'Ecuador',
    'republic of el salvador': 'El Salvador',
    'republic of equatorial guinea': 'Equatorial Guinea',
    'republic of estonia': 'Estonia',
    'republic of fiji': 'Fiji',
    'republic of finland': 'Finland',
    'republic of ghana': 'Ghana',
    'republic of guatemala': 'Guatemala',
    'republic of guinea': 'Guinea',
    'republic of guinea bissau': 'Guinea-Bissau',
    'republic of haiti': 'Haiti',
    'republic of honduras': 'Honduras',
    'republic of iceland': 'Iceland',
    'republic of india': 'India',
    'republic of indonesia': 'Indonesia',
    'republic of iraq': 'Iraq',
    'republic of ireland': 'Ireland',
    'republic of kazakhstan': 'Kazakhstan',
    'republic of kenya': 'Kenya',
    'republic of kiribati': 'Kiribati',
    'republic of korea': 'South Korea',
    'republic of kosovo': 'Kosovo',
    'republic of latvia': 'Latvia',
    'republic of liberia': 'Liberia',
    'republic of lithuania': 'Lithuania',
    'republic of madagascar': 'Madagascar',
    'republic of malawi': 'Malawi',
    'republic of mali': 'Mali',
    'republic of malta': 'Malta',
    'republic of mauritius': 'Mauritius',
    'republic of moldova': 'Moldova',
    'republic of mozambique': 'Mozambique',
    'republic of namibia': 'Namibia',
    'republic of nauru': 'Nauru',
    'republic of nicaragua': 'Nicaragua',
    'republic of niger': 'Niger',
    'republic of north macedonia': 'North Macedonia',
    'republic of palau': 'Palau',
    'republic of panama': 'Panama',
    'republic of paraguay': 'Paraguay',
    'republic of peru': 'Peru',
    'republic of poland': 'Poland',
    'republic of rwanda': 'Rwanda',
    'republic of san marino': 'San Marino',
    'republic of senegal': 'Senegal',
    'republic of serbia': 'Serbia',
    'republic of seychelles': 'Seychelles',
    'republic of sierra leone': 'Sierra Leone',
    'republic of singapore': 'Singapore',
    'republic of slovenia': 'Slovenia',
    'republic of south africa': 'South Africa',
    'republic of south sudan': 'South Sudan',
    'republic of suriname': 'Suriname',
    'republic of tajikistan': 'Tajikistan',
    'republic of the congo': 'Congo',
    'republic of the gambia': 'Gambia',
    'republic of the maldives': 'Maldives',
    'republic of the marshall islands': 'Marshall Islands',
    'republic of the philippines': 'Philippines',
    'republic of the sudan': 'Sudan',
    'republic of the union of myanmar': 'Myanmar',
    'republic of trinidad and tobago': 'Trinidad and Tobago',
    'republic of tunisia': 'Tunisia',
    'republic of turkey': 'Türkiye',
    'republic of turkiye': 'Türkiye',
    'republic of uganda': 'Uganda',
    'republic of uzbekistan': 'Uzbekistan',
    'republic of vanuatu': 'Vanuatu',
    'republic of yemen': 'Yemen',
    'republic of zambia': 'Zambia',
    'republic of zimbabwe': 'Zimbabwe',
    'republica argentina': 'Argentina',
    'republica bolivariana de venezuela': 'Venezuela',
    'republica da guine bissau': 'Guinea-Bissau',
    'republica da guine equatorial': 'Equatorial Guinea',
    'republica de angola': 'Angola',
    'republica de cabo verde': 'Cape Verde',
    'republica de chile': 'Chile',
    'republica de colombia': 'Colombia',
    'republica de costa rica': 'Costa Rica',
    'republica de cuba': 'Cuba',
    'republica de el salvador': 'El Salvador',
    'republica de guinea ecuatorial': 'Equatorial Guinea',
    'republica de honduras': 'Honduras',
    'republica de mocambique': 'Mozambique',
    'republica de nicaragua': 'Nicaragua',
    'republica de panama': 'Panama',
    'republica del ecuador': 'Ecuador',
    'republica del paraguay': 'Paraguay',
    'republica del peru': 'Peru',
    'republica democratica de sao tome e principe': 'São Tomé and Príncipe',
    'republica democratica de timor leste': 'Timor-Leste',
    'republica federativa do brasil': 'Brazil',
    'republica moldova': 'Moldova',
    'republica oriental del uruguay': 'Uruguay',
    'republica portuguesa': 'Portugal',
    'republiek suriname': 'Suriname',
    'republik indonesia': 'Indonesia',
    'republik singapura': 'Singapore',
    'republika demokratika timor leste': 'Timor-Leste',
    'republika hrvatska': 'Croatia',
    'republika ng pilipinas': 'Philippines',
    'republika slovenija': 'Slovenia',
    'republika srbija': 'Serbia',
    'republika yuburundi': 'Burundi',
    'republiken finland': 'Finland',
    'republique centrafricaine': 'Central African Republic',
    'republique de cote divoire': 'Ivory Coast',
    'republique de djibouti': 'Djibouti',
    'republique de guinee': 'Guinea',
    'republique de guinee equatoriale': 'Equatorial Guinea',
    'republique de madagascar': 'Madagascar',
    'republique de maurice': 'Mauritius',
    'republique de vanuatu': 'Vanuatu',
    'republique des seychelles': 'Seychelles',
    'republique dhaiti': 'Haiti',
    'republique du benin': 'Benin',
    'republique du burundi': 'Burundi',
    'republique du cameroun': 'Cameroon',
    'republique du mali': 'Mali',
    'republique du rwanda': 'Rwanda',
    'republique du senegal': 'Senegal',
    'republique du tchad': 'Chad',
    'republique francaise': 'France',
    'republique gabonaise': 'Gabon',
    'republique togolaise': 'Togo',
    'repubulika yu rwanda': 'Rwanda',
    'respublika kazakhstan': 'Kazakhstan',
    'reunion': 'Réunion',
    'reunion island': 'Réunion',
    'ribaberiki kiribati': 'Kiribati',
    'ripablik blong vanuatu': 'Vanuatu',
    'ripublik naoero': 'Nauru',
    'romania': 'Romania',
    'roumania': 'Romania',
    'royaume de belgique': 'Belgium',
    'rsa': 'South Africa',
    'rumania': 'Romania',
    'russia': 'Russia',
    'russian federation': 'Russia',
    'rwanda': 'Rwanda',
    'rzeczpospolita polska': 'Poland',
    'sahrawi arab democratic republic': 'Western Sahara',
    'saint barthelemy': 'Saint Barthélemy',
    'saint helena': 'Saint Helena, Ascension and Tristan da Cunha',
    'saint helena ascension and tristan da cunha': 'Saint Helena, Ascension and Tristan da Cunha',
    'saint kitts and nevis': 'Saint Kitts and Nevis',
    'saint lucia': 'Saint Lucia',
    'saint martin': 'Saint Martin',
    'saint martin (french part)': 'Saint Martin',
    'saint pierre and miquelon': 'Saint Pierre and Miquelon',
    'saint vincent and the grenadines': 'Saint Vincent and the Grenadines',
    'sakartvelo': 'Georgia',
    'saltanat ʻuman': 'Oman',
    'samoa': 'Samoa',
    'samoa amelika': 'American Samoa',
    'san marino': 'San Marino',
    'sankattan siha na islas marianas': 'Northern Mariana Islands',
    'sao tome and principe': 'São Tomé and Príncipe',
    'sarnam': 'Suriname',
    'sathalanalat paxathipatai paxaxon lao': 'Laos',
    'saudi': 'Saudi Arabia',
    'saudi arabia': 'Saudi Arabia',
    'schweiz': 'Switzerland',
    'senegal': 'Senegal',
    'serbia': 'Serbia',
    'seychelles': 'Seychelles',
    'shqiperi': 'Albania',
    'shqiperia': 'Albania',
    'shqipnia': 'Albania',
    'sierra leone': 'Sierra Leone',
    'singapore': 'Singapore',
    'singapura': 'Singapore',
    'sint maarten': 'Sint Maarten',
    'sint maarten (dutch part)': 'Sint Maarten',
    'slovak republic': 'Slovakia',
    'slovakia': 'Slovakia',
    'slovenia': 'Slovenia',
    'slovenska republika': 'Slovakia',
    'socialist republic of vietnam': 'Vietnam',
    'solomon islands': 'Solomon Islands',
    'somalia': 'Somalia',
    'somers isles': 'Bermuda',
    'south africa': 'South Africa',
    'south georgia': 'South Georgia',
    'south georgia and the south sandwich islands': 'South Georgia',
    'south korea': 'South Korea',
    'south sudan': 'South Sudan',
    'spain': 'Spain',
    'sranangron': 'Suriname',
    'srbija': 'Serbia',
    'sri lanka': 'Sri Lanka',
    'st barthelemy': 'Saint Barthélemy',
    'st helena ascension and tristan da cunha': 'Saint Helena, Ascension and Tristan da Cunha',
    'state of eritrea': 'Eritrea',
    'state of israel': 'Israel',
    'state of kuwait': 'Kuwait',
    'state of libya': 'Libya',
    'state of palestine': 'Palestine',
    'state of qatar': 'Qatar',
    'stato della citta del vaticano': 'Vatican City',
    'sudan': 'Sudan',
    'suid afrika': 'South Africa',
    'suisse': 'Switzerland',
    'sultanate of oman': 'Oman',
    'suomen tasavalta': 'Finland',
    'suomi': 'Finland',
    'suriname': 'Suriname',
    'svalbard and jan mayen': 'Svalbard and Jan Mayen',
    'svalbard and jan mayen islands': 'Svalbard and Jan Mayen',
    'svalbard og jan mayen': 'Svalbard and Jan Mayen',
    'svizra': 'Switzerland',
    'svizzera': 'Switzerland',
    'swatini': 'Eswatini',
    'swaziland': 'Eswatini',
    'sweden': 'Sweden',
    'swiss confederation': 'Switzerland',
    'switzerland': 'Switzerland',
    'syria': 'Syria',
    'syrian arab republic': 'Syria',
    'taiwan': 'Taiwan',
    'tajikistan': 'Tajikistan',
    'tanezroft tutrimt': 'Western Sahara',
    'tanzania': 'Tanzania',
    'tanzania united republic of': 'Tanzania',
    'tchad': 'Chad',
    'teratri of norfk ailen': 'Norfolk Island',
    'territoire des iles wallis et futuna': 'Wallis and Futuna',
    'territory of christmas island': 'Christmas Island',
    'territory of norfolk island': 'Norfolk Island',
    'territory of the cocos (keeling) islands': 'Cocos (Keeling) Islands',
    'territory of the french southern and antarctic lands': 'French Southern and Antarctic Lands',
    'territory of the wallis and futuna islands': 'Wallis and Futuna',
    'teta paraguai': 'Paraguay',
    'teta volivia': 'Bolivia',
    'thai': 'Thailand',
    'thailand': 'Thailand',
    'the abode of peace': 'Brunei',
    'the bermudas': 'Bermuda',
    'the former yugoslav republic of macedonia': 'North Macedonia',
    'the islands of bermuda': 'Bermuda',
    'the netherlands': 'Netherlands',
    'timor': 'Timor-Leste',
    'timor leste': 'Timor-Leste',
    'timor lorosae': 'Timor-Leste',
    'tocikiston': 'Tajikistan',
    'togo': 'Togo',
    'togolese': 'Togo',
    'togolese republic': 'Togo',
    'tokelau': 'Tokelau',
    'tonga': 'Tonga',
    'trinidad and tobago': 'Trinidad and Tobago',
    'tunisia': 'Tunisia',
    'tunisian republic': 'Tunisia',
    'turkiye': 'Türkiye',
    'turkiye cumhuriyeti': 'Türkiye',
    'turkmenistan': 'Turkmenistan',
    'turks and caicos islands': 'Turks and Caicos Islands',
    'tuvalu': 'Tuvalu',
    'u s': 'United States',
    'uae': 'United Arab Emirates',
    'udzima wa komori': 'Comoros',
    'uganda': 'Uganda',
    'uk': 'United Kingdom',
    'ukraine': 'Ukraine',
    'ukrayina': 'Ukraine',
    'umbuso weswatini': 'Eswatini',
    'union des comores': 'Comoros',
    'union of the comoros': 'Comoros',
    'united arab emirates': 'United Arab Emirates',
    'united kingdom': 'United Kingdom',
    'united kingdom of great britain and northern ireland': 'United Kingdom',
    'united mexican states': 'Mexico',
    'united republic of tanzania': 'Tanzania',
    'united states': 'United States',
    'united states minor outlying islands': 'United States Minor Outlying Islands',
    'united states of america': 'United States',
    'united states virgin islands': 'United States Virgin Islands',
    'uruguay': 'Uruguay',
    'us': 'United States',
    'usa': 'United States',
    'uzbekistan': 'Uzbekistan',
    'vanuatu': 'Vanuatu',
    'vatican': 'Vatican City',
    'vatican city': 'Vatican City',
    'vatican city state': 'Vatican City',
    'venezuela': 'Venezuela',
    'venezuela bolivarian republic of': 'Venezuela',
    'viet nam': 'Vietnam',
    'vietnam': 'Vietnam',
    'virgin islands': 'British Virgin Islands',
    'virgin islands british': 'British Virgin Islands',
    'virgin islands of the united states': 'United States Virgin Islands',
    'virgin islands us': 'United States Virgin Islands',
    'viti': 'Fiji',
    'waitu kubuli': 'Dominica',
    'wallis and futuna': 'Wallis and Futuna',
    'western sahara': 'Western Sahara',
    'weswatini': 'Eswatini',
    'wuliwya': 'Bolivia',
    'wuliwya suyu': 'Bolivia',
    'yemen': 'Yemen',
    'yemeni republic': 'Yemen',
    'zambia': 'Zambia',
    'zhongguo': 'China',
    'zhonghua': 'China',
    'zhonghua minguo': 'Taiwan',
    'zhonghua renmin gongheguo': 'China',
    'zimbabwe': 'Zimbabwe',
    'ʁɛpublika de anɡɔla': 'Angola',
    'ʾertra': 'Eritrea',
    'ʾityoppya': 'Ethiopia',
    'ελληνικη δημοκρατια': 'Greece',
    'κυπριακη δημοκρατια': 'Cyprus',
    'белоруссия': 'Belarus',
    'босна и херцеговина': 'Bosnia and Herzegovina',
    'казахстан': 'Kazakhstan',
    'киргизия': 'Kyrgyzstan',
    'кыргыз республикасы': 'Kyrgyzstan',
    'република българия': 'Bulgaria',
    'република косово': 'Kosovo',
    'република северна македонија': 'North Macedonia',
    'република србија': 'Serbia',
    'республика белоруссия': 'Belarus',
    'республика казахстан': 'Kazakhstan',
    'россииская федерация': 'Russia',
    'србија': 'Serbia',
    'узбекистон республикаси': 'Uzbekistan',
    'қазақстан республикасы': 'Kazakhstan',
    'ҷумҳурии тоҷикистон': 'Tajikistan',
    'հայաստանի հանրապետություն': 'Armenia',
    'இநதியா': 'India',
    'ราชอาณาจักรไทย': 'Thailand',
    '남조선': 'South Korea',
    '북조선': 'North Korea',
    '조선민주주의인민공화국': 'North Korea',
    'ሃገረ ኤርትራ': 'Eritrea',
    'የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ': 'Ethiopia',
    '中华人民共和国': 'China',
    '中華人民共和國澳門特別行政區': 'Macau',
    '中華民國': 'Taiwan',
    '新加坡共和国': 'Singapore',
}
